version: '3'

services:
  hidden-database:
    container_name: hidden-database
    image: postgres:12
    environment:
      POSTGRES_DB: HiddenJVC
      POSTGRES_USER: hidden-jvc-user
      POSTGRES_PASSWORD: aze
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  hidden-pgadmin:
    container_name: hidden-pgadmin
    image: dpage/pgadmin4:4.21
    depends_on:
      - hidden-database
    environment:
      PGADMIN_DEFAULT_EMAIL: hidden@jvc
      PGADMIN_DEFAULT_PASSWORD: aze
    ports:
      - "8181:80"
