version: '3'

services:
  hidden-database:
    container_name: hidden-database
    image: postgres:12
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  hidden-pgadmin:
    container_name: hidden-pgadmin
    image: dpage/pgadmin4:4.24
    depends_on:
      - hidden-database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8181:80"
